{ SPDX-License-Identifier: MIT
  Copyright (c) 2021 mr-highball }
unit ensemble_studio_server;

{$mode delphi}{$H+}
{$IFDEF PAS2JS}{$FATAL the download server requires native FPC}{$ENDIF}

interface

uses
  SysUtils, wfc_serve_http;

type
  { Dedicated, opt-in local renderer. The capability is generated by the OS,
    changes with each host process, and is not a WFC seed or network login.
    This host is for a trusted machine/LAN, never an Internet service. }
  TEnsembleStudioServer = class(TWfcServeExtension)
  private
    FToken: String;
    function HasCapability(const ATarget: String): Boolean;
  public
    constructor Create;
    function HandleRequest(const ARequest: TWfcServeRequest;
      const AResponse: TWfcServeResponse): Boolean; override;
  end;

implementation

uses
  wfc_browser_socket, ensemble_studio_http, ensemble_studio_stream,
  wfc_music_audio, wfc_music_audio_stream, wfc_music_arrangement;

type
  THttpWaveSink = class(TWfcMusicAudioByteSink)
  private
    FResponse: TWfcServeResponse;
  public
    constructor Create(const AResponse: TWfcServeResponse);
    procedure WriteBytes(const ABytes: array of Byte); override;
  end;

constructor THttpWaveSink.Create(const AResponse: TWfcServeResponse);
begin
  inherited Create;
  FResponse := AResponse;
end;

procedure THttpWaveSink.WriteBytes(const ABytes: array of Byte);
begin
  if Length(ABytes) > 0 then FResponse.WriteBytes(ABytes[0], Length(ABytes));
end;

constructor TEnsembleStudioServer.Create;
var
  LBytes: array[0..15] of Byte;
  I: Integer;
begin
  inherited Create;
  WfcBrowserRandomBytes(LBytes[0], SizeOf(LBytes));
  for I := 0 to High(LBytes) do
    FToken := FToken + LowerCase(IntToHex(LBytes[I], 2));
end;

function TEnsembleStudioServer.HasCapability(const ATarget: String): Boolean;
var
  I, LStart, LEnd, LCount: Integer;
  LPart: String;
begin
  Result := False;
  LCount := 0;
  I := Pos('?', ATarget);
  if I = 0 then Exit;
  LStart := I + 1;
  while LStart <= Length(ATarget) do
  begin
    LEnd := LStart;
    while (LEnd <= Length(ATarget)) and (ATarget[LEnd] <> '&') do Inc(LEnd);
    LPart := Copy(ATarget, LStart, LEnd - LStart);
    if Copy(LPart, 1, 6) = 'token=' then
    begin
      Inc(LCount);
      if (LCount <> 1) or (Copy(LPart, 7, MaxInt) <> FToken) then Exit;
    end;
    LStart := LEnd + 1;
  end;
  Result := LCount = 1;
end;

procedure TextResponse(const AResponse: TWfcServeResponse;
  const AStatus: Integer; const AText: String;
  const AType: String = 'text/plain; charset=utf-8');
begin
  AResponse.BeginResponse(AStatus, Length(AText), AType);
  if not AResponse.HeadOnly then AResponse.WriteText(AText);
  AResponse.Finish;
end;

procedure SendWave(const ARequest: TEnsembleStudioHttpRequest;
  const AResponse: TWfcServeResponse);
var
  LSource: TEnsembleStudioPcmStream;
  LSink: THttpWaveSink;
  LWave: TWfcMusicWaveStream;
  LSamples: TWfcMusicPcm16Samples;
  LStep: TWfcMusicArrangementStep;
begin
  LSource := nil;
  LSink := nil;
  LWave := nil;
  try
    if not AResponse.HeadOnly then
    begin
      LSource := TEnsembleStudioPcmStream.Create(ARequest.Plan, ARequest.Options);
      { Detect initial model/planning/solve failure before sending a success
        header. Only one PCM block is prefetched, independently of duration. }
      LStep := LSource.NextSamples(LSamples);
      if LStep <> wmaspProduced then
        raise EEnsembleStudioStream.Create('initial stream generation failed');
    end;
    AResponse.BeginResponse(200, EnsembleStudioHttpWaveBytes(ARequest.Plan),
      'audio/wav', EnsembleStudioHttpFileName(ARequest));
    if AResponse.HeadOnly then
    begin
      AResponse.Finish;
      Exit;
    end;
    LSink := THttpWaveSink.Create(AResponse);
    LWave := TWfcMusicWaveStream.Create(LSink,
      ENSEMBLE_STUDIO_STREAM_SAMPLE_RATE, ARequest.Plan.ExpectedFrames);
    repeat
      case LStep of
        wmaspProduced: LWave.AppendSamples(LSamples);
        wmaspCompleted: Break;
      else
        raise EEnsembleStudioStream.Create('stream generation did not complete');
      end;
      LStep := LSource.NextSamples(LSamples);
    until False;
    if (LSource.EmittedFrames <> ARequest.Plan.ExpectedFrames) or
        (LWave.FrameCount <> ARequest.Plan.ExpectedFrames) then
      raise EEnsembleStudioStream.Create('stream frame count differs from preflight');
    LWave.Finish;
    { The final HTTP body byte is released only after source and container
      completion. An exception/disconnect never pads a truncated download. }
    AResponse.Finish;
  finally
    LWave.Free;
    LSink.Free;
    if LSource <> nil then LSource.Cancel;
    LSource.Free;
  end;
end;

function TEnsembleStudioServer.HandleRequest(const ARequest: TWfcServeRequest;
  const AResponse: TWfcServeResponse): Boolean;
var
  LRequest: TEnsembleStudioHttpRequest;
begin
  Result := True;
  if ARequest.RelativePath = Copy(ENSEMBLE_STUDIO_HTTP_CAPABILITIES_PATH, 2, MaxInt) then
  begin
    if ARequest.Target <> ENSEMBLE_STUDIO_HTTP_CAPABILITIES_PATH then
      TextResponse(AResponse, 400, 'Invalid capabilities request.'#10)
    else
      TextResponse(AResponse, 200, '{"version":1,"wavePath":"' +
        ENSEMBLE_STUDIO_HTTP_WAVE_PATH + '","token":"' + FToken + '"}'#10,
        'application/json');
    Exit;
  end;
  if ARequest.RelativePath <> Copy(ENSEMBLE_STUDIO_HTTP_WAVE_PATH, 2, MaxInt) then
    Exit(False);
  if not HasCapability(ARequest.Target) then
  begin
    TextResponse(AResponse, 403, 'Open Ensemble Studio on this server before downloading.'#10);
    Exit;
  end;
  try
    LRequest := ParseEnsembleStudioHttpRequest(ARequest.Target);
  except
    on E: EEnsembleStudioHttp do
    begin
      TextResponse(AResponse, 400, 'Invalid ensemble stream settings.'#10);
      Exit;
    end;
  end;
  try
    SendWave(LRequest, AResponse);
  except
    on E: Exception do
    begin
      if AResponse.Started then raise;
      { No exception text, seed, query or capability is reflected into HTML. }
      TextResponse(AResponse, 500, 'Ensemble generation failed before download. Check the stream settings.'#10);
    end;
  end;
end;

end.
